version: '3.5'

services:
    blt:
      command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
      volumes:
        - ./:/usr/src/app
      env_file: .app.env
      links:
        - postgres

    postgres:
      restart: always
      image: postgres:latest
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data/
  
volumes:
    pgdata: